---
- name: Copy config file
  copy:
    src: "nginx.conf"
    dest: "/etc/nginx/nginx.conf"

- name: Copy hardened defaults
  copy:
    src: "harden.conf"
    dest: "/etc/nginx/harden.conf"

- name: Ensure HTTP port is available
  import_role:
    name: common_roles/free_port
  vars:
    port_to_free: "{{ ports.http }}"

- name: Ensure HTTPS port is available
  import_role:
    name: common_roles/free_port
  vars:
    port_to_free: "{{ ports.https }}"

- name: Enable and restart nginx
  service:
    name: nginx
    enabled: true
    state: restarted
