---
- name: Copy config file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Clear HTTP port
  shell: "sudo lsof -i tcp:{{ ports.http }} | awk 'NR!=1 {print $2}' | xargs sudo kill &> /dev/null"
  ignore_errors: true

- name: Restart nginx
  service:
    name: nginx
    state: restarted
    enabled: true
