---
basic_packages:
  - curl
  - delta
  - docker
  - docker-compose
  - exa
  - expect
  - fzf
  - git
  - htop
  - libjpeg-dev
  - libxtst-dev
  - lua5.4
  - lsof
  - neovim
  - python3-pip
  - ripgrep
  - rsync
  - stow
  - tree
  - ufw
  - vifm
  - zlib1g-dev
  - zsh

dotfiles: https://github.com/ericdriussi/dotfiles.git
