stages:
  - setup
  - run

setup_environment:
  stage: setup
  script:
    - |
      cat <<EOF >.env.yml
      ---
      domain: "localhost"
      email: "your@email.address"
      nextcloud_username: "admin_user"
      nextcloud_password: "admin_pwd"
      gitea_username: "admin_user"
      gitea_password: "admin_pwd"
      vaultwarden_password: "admin_panel_pwd"
      ssh_key: "~/.ssh/id_rsa"
      dotfiles_repo: "https://gitlab.com/ericdriussi/dotfiles.git"
      EOF
  artifacts:
    paths:
      - .env.yml

run_job:
  stage: run
  image: jrei/systemd-debian:12 # TODO: try debian:12 or bookworm instead
  dependencies:
    - setup_environment
  script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - apt update
    - apt install -y curl openssh-server # TODO: install in ssh task?
    - mkdir -p /run/sshd ./HYO
    - cp .env.yml ./HYO/.env.yml
    # TODO: point to master branch, rm --connection=local flag
    - curl -sSL https://gitlab.com/ericdriussi/host-your-own/-/raw/ci/init.sh | bash -s -- --connection=local --skip-tags=ignore-ci
