stages:
  - setup
  - run

setup_environment:
  stage: setup
  script:
    - |
      cat <<EOF >.env.yml
      ---
      username: "ansible"
      domain: "localhost"
      email: "an@email.address"
      nextcloud_username: "admin_user"
      nextcloud_password: "admin_pwd"
      gitea_username: "admin_user"
      gitea_password: "admin_pwd"
      vaultwarden_password: "admin_panel_pwd"
      ssh_key: "~/.ssh/id_rsa"
      dotfiles_repo: "https://gitlab.com/ericdriussi/dotfiles.git"
      EOF
  artifacts:
    paths:
      - .env.yml

run_job:
  stage: run
  image: debian:12
  dependencies:
    - setup_environment
  script:
    - apt update
    - apt install -y curl git
    - mkdir -p /run/sshd
    - git clone https://gitlab.com/ericdriussi/host-your-own.git host-your-own
    - cp .env.yml host-your-own/.env.yml
    - cd host-your-own && ./init.sh --connection=local --skip-tags=ignore-ci
