stages:
  - build
  - setup
  - run

setup_environment:
  stage: setup
  script:
    - |
      cat <<EOF >.env.yml
      ---
      domain: "localhost"
      email: "your@email.address"
      nextcloud_username: "admin_user"
      nextcloud_password: "admin_pwd"
      gitea_username: "admin_user"
      gitea_password: "admin_pwd"
      vaultwarden_password: "admin_panel_pwd"
      ssh_key: "~/.ssh/id_rsa"
      dotfiles_repo: "https://github.com/ericdriussi/dotfiles.git"
      EOF
  artifacts:
    paths:
      - .env.yml

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t ci-image .
    - mkdir -p image
    - docker save ci-image > image/HYO.tar
  artifacts:
    paths:
      - image

run_job:
  stage: run
  image: docker:latest
  dependencies:
    - setup_environment
    - build_image
  script:
    - docker load -i image/HYO.tar
    - docker run --name HYO -d HYO

    - docker exec HYO apt update
    - docker exec HYO apt install -y curl openssh-server
    - docker exec HYO mkdir -p /run/sshd ./HYO
    - docker exec HYO cp .env.yml ./HYO/.env.yml
    - docker exec HYO bash -c "curl -sSL https://gitlab.com/ericdriussi/host-your-own/-/raw/ci/init.sh | bash -s -- --connection=local"
