stages:
  - build
  - setup
  - run

setup_environment:
  stage: setup
  script:
    - |
      cat <<EOF >.env.yml
      ---
      domain: "localhost"
      email: "your@email.address"
      nextcloud_username: "admin_user"
      nextcloud_password: "admin_pwd"
      gitea_username: "admin_user"
      gitea_password: "admin_pwd"
      vaultwarden_password: "admin_panel_pwd"
      ssh_key: "~/.ssh/id_rsa"
      dotfiles_repo: "https://github.com/ericdriussi/dotfiles.git"
      EOF
  artifacts:
    paths:
      - .env.yml

build_image:
 stage: build
 image: docker:latest
 services:
    - docker:dind
 variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
 script:
    - docker build -t ci-image .
    - mkdir image
    - docker save ci-image > image/HYO.tar
 artifacts:
    paths:
      - image

run-job:
  stage: run
  dependencies:
    - setup_environment
  script:
    - docker load -i image/HYO.tar
    - docker run --name HYO -d HYO

    - docker exec HYO bash -c "apt-get update && apt-get install -y curl openssh-server && mkdir -p /run/sshd ./HYO && cp .env.yml ./HYO/.env.yml && curl -sSL https://gitlab.com/ericdriussi/host-your-own/-/raw/ci/init.sh | bash -s -- --connection=local"
    - docker exec HYO apt-get update
    - docker exec HYO apt-get install -y curl openssh-server
    - docker exec HYO mkdir -p /run/sshd ./HYO
    - docker exec HYO cp .env.yml ./HYO/.env.yml
    - docker exec HYO bash -c "curl -sSL https://gitlab.com/ericdriussi/host-your-own/-/raw/ci/init.sh | bash -s -- --connection=local"
