stages:
  - setup
  - run

setup_environment:
  stage: setup
  script:
    - |
      cat <<EOF >.env.yml
      ---
      domain: "localhost"
      email: "your@email.address"
      nextcloud_username: "admin_user"
      nextcloud_password: "admin_pwd"
      gitea_username: "admin_user"
      gitea_password: "admin_pwd"
      vaultwarden_password: "admin_panel_pwd"
      ssh_key: "~/.ssh/id_rsa"
      dotfiles_repo: "https://gitlab.com/ericdriussi/dotfiles.git"
      EOF
  artifacts:
    paths:
      - .env.yml

run_job:
  stage: run
  image: debian:12
  dependencies:
    - setup_environment
  script:
    - apt update
    - apt install -y curl
    - mkdir -p /run/sshd ./HYO
    - cp .env.yml ./HYO/.env.yml
    - curl -sSL https://gitlab.com/ericdriussi/host-your-own/-/raw/master/init.sh | bash -s -- --connection=local --skip-tags=ignore-ci
