---
- hosts: ansible
  name: Server setup
  become: true

  vars_files:
    - .env.yml

  roles:
    - role: harden
      tags:
        - harden

    - role: update
      tags:
        - update

    - role: custom
      tags:
        - custom

    - role: fail2ban
      tags:
        - ban

    - role: nextcloud
      tags:
        - nextcloud

    - role: vault
      tags:
        - vault

    - role: searx
      tags:
        - searx

    - role: website
      become_user: "{{ username }}"
      tags:
        - website

    # TODO.test in prod, might need tinkering with bunker conf
    - role: onion
      tags:
        - onion

    - role: bunker
      tags:
        - bunker
