---
- name: Create user
  hosts: vps
  remote_user: root
  gather_facts: no
  vars_files:
    - .env.yml
  roles:
    - role: user
      tags:
        - user

- name: Server setup
  hosts: vps
  remote_user: "{{ username }}" 
  # TODO.limit sudo
  become: true
  vars_files:
    - .env.yml

  roles:
    - role: harden
      tags:
        - harden

    - role: update
      tags:
        - update

    - role: custom
      tags:
        - custom

    - role: nextcloud
      tags:
        - nextcloud

    - role: vault
      tags:
        - vault

    - role: searx
      tags:
        - searx

    - role: website
      become_user: "{{ username }}"
      tags:
        - website

    - role: onion
      tags:
        - onion

    - role: fail2ban
      tags:
        - ban

    - role: bunker
      tags:
        - bunker
