---

- name: CREATE USER
  tags: user
  hosts: root
  become: true

  tasks:
    - import_tasks: tasks/create-user.yml

- name: SSH CONFIG
  tags: ssh
  hosts: ansible
  become: true

  tasks:
    - import_tasks: tasks/ssh-config.yml

- name: INSTALL ESSENTIALS
  tags: install
  hosts: all

  tasks:
    - import_tasks: tasks/essentials.yml

- name: CONFIG SERVER
  tags: config
  hosts: ansible

  tasks:
    - import_tasks: tasks/server-config.yml

- name: PROVISION SERVER
  tags: provision
  hosts: ansible

  tasks:
    - import_tasks: tasks/server-provision.yml
