---
- hosts: root
  name: Create ansible user
  vars_files:
    - .env.yml

  roles:
    - role: user
      tags:
        - user

- hosts: ansible
  name: Server setup
  become: true

  vars_files:
    - .env.yml

  roles:
    - role: harden
      tags:
        - harden

    - role: update
      tags:
        - update

    - role: custom
      tags:
        - custom

    - role: fail2ban
      tags:
        - ban

    - role: nextcloud
      tags:
        - nextcloud

    - role: vault
      tags:
        - vault

    - role: searx
      tags:
        - searx

    - role: onion
      tags:
        - onion

    - role: bunker
      tags:
        - bunker

- name: NGINX
  tags: nginx
  hosts: ansible
  become: true
  tasks:
    - import_tasks: tasks/nginx.yml
