---
- name: CREATE USER
  tags: user
  hosts: root
  become: true
  tasks:
    - import_tasks: tasks/create-user.yml

- name: SSH CONFIG
  tags: ssh
  hosts: ansible
  become: true
  tasks:
    - import_tasks: tasks/ssh-config.yml

- name: INSTALL ESSENTIALS
  tags: install
  hosts: ansible
  tasks:
    - import_tasks: tasks/essentials.yml

- name: PROVISION SERVER
  tags: provision
  hosts: ansible
  become: true
  tasks:
    - import_tasks: tasks/server-provision.yml

# TODO.Test
- name: FAIL 2 BAN
  tags: ban
  hosts: ansible
  tasks:
    - import_tasks: tasks/fail2ban.yml

- name: NEXTCLOUD
  tags: nextcloud
  hosts: ansible
  become: true
  tasks:
    - import_tasks: tasks/nextcloud.yml

- name: VAULT
  tags: vault
  hosts: ansible
  tasks:
    - import_tasks: tasks/vault.yml

- name: SEARX
  tags: searx
  hosts: ansible
  become: true
  tasks:
    - import_tasks: tasks/searx.yml

- name: SYNC WEBSITE
  tags: website
  hosts: ansible
  tasks:
    - import_tasks: tasks/sync-website.yml

- name: ONION
  tags: onion
  hosts: ansible
  become: true
  tasks:
    - import_tasks: tasks/onion.yml

- name: NGINX
  tags: nginx
  hosts: ansible
  become: true
  tasks:
    - import_tasks: tasks/nginx.yml
