---
- name: CREATE USER
  tags: user
  hosts: root
  become: true
  tasks:
    - import_tasks: tasks/create-user.yml

- name: SSH CONFIG
  tags: ssh
  hosts: ansible
  become: true
  tasks:
    - import_tasks: tasks/ssh-config.yml

- name: INSTALL ESSENTIALS
  tags: install
  hosts: ansible
  tasks:
    - import_tasks: tasks/essentials.yml

- name: PROVISION SERVER
  tags: provision
  hosts: ansible
  become: true
  tasks:
    - import_tasks: tasks/server-provision.yml

- name: BITWARDEN
  tags: bitwarden
  hosts: bitwarden
  tasks:
    - import_tasks: tasks/bitwarden.yml

- name: ONION
  tags: onion
  hosts: ansible
  become: true
  tasks:
    - import_tasks: tasks/onion.yml

- name: NGINX
  tags: nginx
  hosts: ansible
  become: true
  tasks:
    - import_tasks: tasks/nginx.yml
