---
- name: Create docker group
  group:
    name: docker
    state: present

- name: Create {{ username }} user
  user:
    name: "{{ username }}"
    groups:
      - sudo
      - docker
    system: no
    createhome: yes
    home: "/home/{{ username }}"
