---
- name: Create User
  vars:
    has_root_access: false
  block:
    - name: Check root access
      block:
        - name: Check SSH access
          raw: ssh -o BatchMode=yes -o ConnectTimeout=5 "root@{{ ip | default(domain) }}" exit
          register: root_ssh
          ignore_errors: true
          delegate_to: localhost

        - set_fact:
            has_root_access: true
          when: "root_ssh.rc == 0"

    - name: Run tasks
      block:
      - name: Create user
        import_tasks: create.yml

      - name: Sudo and SSH
        import_tasks: priviledges.yml

      when: has_root_access and create_remote_user
