---
- name: UFW deny all except HTTP and HTTPS
  ufw:
    state: enabled
    policy: deny
    rule: allow
    port: "{{ item }}"
  with_items:
    - '80'
    - '443'

- name: UFW limit ssh traffic
  ufw:
    rule: limit
    port: '22'
