- name: disable pwd for ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: restart ssh
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed
