- name: update system
  package:
    update_cache: yes
    upgrade: yes

- name: install basics
  package:
    name: "{{ packages.basic }}"
    state: latest

- name: clone dotfiles
  git:
    repo: 'https://gitlab.com/ericdriussi/dotfiles.git'
    dest: dotfiles
    force: yes

- name: change dotfiles ownership
  file:
    path: dotfiles
    owner: "{{ users.login }}"
    group: "{{ users.login }}"
    state: directory
    recurse: yes

- name: install ueberzug
  pip:
    name: ueberzug

- name: patch vifm with ueberzug
  git:
    repo: 'https://github.com/cirala/vifmimg.git'
    dest: ./dotfiles/vifm/.config/vifm/vifmimg
    force: yes

- name: zsh-autosuggestions
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: ./dotfiles/base/.custom-zsh/plugins/zsh-autosuggestions
    force: yes

- name: zsh-syntax-highlighting
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: ./dotfiles/base/.custom-zsh/plugins/zsh-syntax-highlighting
    force: yes

- name: default to zsh
  user:
    name: "{{ users.login }}"
    shell: /usr/bin/zsh

- name: mkdir nvim
  file:
    path: .config/nvim
    owner: ansible
    group: ansible
    state: directory

- name: download NVIM
  get_url:
    url: https://gitlab.com/ericdriussi/nvim/-/raw/master/init.vim
    dest: .config/nvim/init.vim
    owner: "{{ users.login }}"
    group: "{{ users.login }}"
