---
- name: Create Docker Group
  group:
    name: docker
    state: present

- name: Create {{ users.login }} User
  user:
    name: "{{ users.login }}"
    groups:
      - sudo
      - docker
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: "/home/{{ users.login }}"

- name: Password-less sudo for {{ users.login }}
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ users.login }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Setup ssh for {{ users.login }}
  authorized_key:
    user: "{{ users.login }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
