- name: Update System
  package:
    update_cache: yes
    upgrade: yes

- name: Create {{ users.login }} User
  user:
    name: "{{ users.login }}"
    password: "{{ pwd | password_hash('sha512') }}"
    groups:
      - sudo
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: "/home/{{ users.login }}"

- name: Pwdless Sudo for {{ users.login }}
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ users.login }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Setup ssh For {{ users.login }}
  authorized_key:
    user: "{{ users.login }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
