---
- name: Create Docker Group
  group:
    name: docker
    state: present

- name: Create {{ username }} User
  user:
    name: "{{ username }}"
    groups:
      - sudo
      - docker
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: "/home/{{ username }}"

- name: Password-less sudo for {{ username }}
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Setup ssh for {{ username }}
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
