---
- name: Create Docker Group
  group:
    name: docker
    state: present

- name: Create {{ login_user }} User
  user:
    name: "{{ login_user }}"
    groups:
      - sudo
      - docker
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: "/home/{{ login_user }}"

- name: Password-less sudo for {{ login_user }}
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ login_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Setup ssh for {{ login_user }}
  authorized_key:
    user: "{{ login_user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
