---
- name: Update system
  become: true
  package:
    update_cache: yes
    upgrade: yes

- name: Install basic packages
  become: true
  package:
    name: "{{ packages.basic }}"
    state: latest

- name: Install ueberzug
  pip:
    name: ueberzug

- name: Clone dotfiles
  git:
    repo: "{{ dotfiles }}"
    dest: dotfiles
    force: yes
    track_submodules: yes

- name: Set zsh as default shell
  become: true
  user:
    name: "{{ login_user }}"
    shell: /usr/bin/zsh

- name: Create Nvim directory
  file:
    path: "/home/{{ login_user }}/config/nvim"
    state: directory

- name: Transfer Nvim config
  copy:
    src: init.vim
    dest: "/home/{{ login_user }}/config/nvim/"

- name: Copy Nvim config for root user
  become: true
  shell: mkdir -p /root/.config/nvim/ && cp /home/{{ login_user }}/.config/nvim/init.vim '$_'

- name: Transfer zsh config
  copy:
    src: zshrc
    dest: "/home/{{ login_user }}/dotfiles/base/.zshrc"

- name: Unstow dotfiles
  shell:
    cmd: "stow -R {{ item }}"
    chdir: dotfiles
  with_items:
    - base
    - fontconfig
    - vifm
