---
- name: Update system
  become: true
  package:
    update_cache: yes
    upgrade: yes

- name: Install basic packages
  become: true
  package:
    name: "{{ packages.basic }}"
    state: latest

- name: Install ueberzug
  pip:
    name: ueberzug

- name: Clone dotfiles
  git:
    repo: "{{ dotfiles }}"
    dest: dotfiles
    force: yes
    track_submodules: yes

- name: Set zsh as default shell
  become: true
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh

# TODO.Actually clone nvim config
- name: Create Nvim directory
  file:
    path: "/home/{{ username }}/.config/nvim"
    state: directory

- name: Transfer Nvim config
  copy:
    src: init.vim
    dest: "/home/{{ username }}/.config/nvim/"

# TODO.Copy whole dir and rename base-init to init
- name: Copy Nvim config for root user
  become: true
  shell: 'mkdir -p /root/.config/nvim/ && cp /home/{{ username }}/.config/nvim/init.vim /root/.config/nvim/'

- name: Unstow dotfiles
  shell:
    cmd: "stow -R {{ item }}"
    chdir: dotfiles
  with_items:
    - base
    - fontconfig
    - vifm
