---
- name: Update system
  become: true
  package:
    update_cache: yes
    upgrade: yes

- name: Install basic packages
  become: true
  package:
    name: "{{ packages.basic }}"
    state: latest

- name: Clone dotfiles
  git:
    repo: "{{ dotfiles }}"
    dest: dotfiles
    force: yes
    track_submodules: yes

- name: Set zsh as default shell
  become: true
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  with_items:
    - "{{ username }}"
    - root

- name: Clone nvim config
  git:
    repo: "{{ nvim_config }}"
    dest: ~/.config/nvim
    force: yes

- name: Copy for root user
  become: true
  copy:
    src: "/home/{{ username }}/{{ item.src }}"
    dest: "/root/{{ item.dest }}"
    remote_src: yes
  with_items:
    - {src: "dotfiles/base/.zshrc", dest: ".zshrc"}
    - {src: "dotfiles/custom-zsh/.config/custom-zsh", dest: ".config/"}
    - {src: ".config/nvim", dest: ".config/"}

- name: Set base init for root
  become: true
  shell: 'rm /root/.config/nvim/init.vim && cp /root/.config/nvim/base-init.vim /root/.config/nvim/init.vim'

- name: Unstow dotfiles
  shell:
    cmd: "stow -R {{ item }}"
    chdir: dotfiles
  with_items:
    - base
    - fontconfig
    - vifm
