---
- name: Update System
  become: true
  package:
    update_cache: yes
    upgrade: yes

- name: Install Basic Packages
  become: true
  package:
    name: "{{ packages.basic }}"
    state: latest

- name: Install Ueberzug
  pip:
    name: ueberzug

- name: Clone Dotfiles
  git:
    repo: 'https://gitlab.com/ericdriussi/dotfiles.git'
    dest: dotfiles
    force: yes
    track_submodules: yes

- name: Default To zsh
  become: true
  user:
    name: "{{ users.login }}"
    shell: /usr/bin/zsh

- name: Create Nvim Dir
  file:
    path: .config/nvim
    state: directory

- name: Clone Nvim Config
  get_url:
    url: https://gitlab.com/ericdriussi/nvim/-/raw/master/init.vim
    dest: .config/nvim/init.vim

- name: Modify zshrc
  shell: "sed -Ee '/.*NVM.*/d' -Ee '/.*NODE.*/d' -Ee '/.*lua.*/d' ./dotfiles/base/.zshrc -i"

- name: Modify init.vim
  shell: "sed '/^source.*/d' ./.config/nvim/init.vim -i"

- name: Stow Basic Dotfiles
  shell:
    cmd: "stow -R {{ item }}"
    chdir: dotfiles
  with_items:
    - base
    - fontconfig
    - vifm
