---
- name: Install fail2ban
  package:
    name: fail2ban
    state: present

- name: Disable e-mail notifications on jail stop and start
  copy:
    src: "fail2ban"
    dest: "/etc/fail2ban/action.d/sendmail-common.local"
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart fail2ban

- name: Install the jail file
  template:
    src: "jail"
    dest: "/etc/fail2ban/jail.local"
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart fail2ban

- name: Make sure the fail2ban systemd service is enabled and started
  service:
    name: fail2ban
    state: started
    enabled: yes
