---
- name: Setup Nextcloud port
  shell: "snap set nextcloud ports.http={{ internal_ports.nextcloud }}"
  when: install.changed

- name: Setup Nextcloud admin account
  shell: '/snap/bin/nextcloud.manual-install {{ username }} {{ pwd }}'
  when: install.changed

- name: Ensure Nextcloud prefers HTTPS
  shell: '/snap/bin/nextcloud.occ config:system:set overwriteprotocol --value="https"'
  when: install.changed

- name: Config Nextcloud trusted domain
  lineinfile:
    dest: /var/snap/nextcloud/current/nextcloud/config/config.php
    regexp: ".*0 => 'localhost'.*"
    line: "1 => 'cloud.{{ domain }}'"
