---
- name: Delete default config
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default

- name: Transfer nginx server file
  copy:
    src: "{{ item }}"
    dest: /etc/nginx/sites-enabled/
  with_items:
    - nginx-website
    - nginx-onion
    - nginx-nextcloud
    - nginx-bitwarden

- name: Retrieve Onion Address
  command: cat /var/lib/tor/hidden_service/hostname
  register: address

- name: Set onion address
  lineinfile:
    dest: "/etc/nginx/sites-enabled/nginx-onion"
    regexp: ".*server_name.*"
    line: "        server_name {{ address.stdout }};"

- name: Parse website config
  lineinfile:
    dest: "/etc/nginx/sites-enabled/nginx-website"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '.*server_name .*', line: '        server_name {{ domain }} www.{{ domain }};' }
    - { regexp: '.*add_header.*', line: '    add_header Onion-Location http://{{ address.stdout }}$request_uri;' }

- name: Parse nextcloud config
  lineinfile:
    dest: "/etc/nginx/sites-enabled/nginx-nextcloud"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '.*server_name .*', line: '        server_name cloud.{{ domain }} www.cloud.{{ domain }};' }
    - { regexp: '.*proxy_pass .*', line: '        proxy_pass          http://127.0.0.1:{{ internal_ports.nextcloud }};' }

- name: Parse bitwarden config
  lineinfile:
    dest: "/etc/nginx/sites-enabled/nginx-bitwarden"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '.*proxy_pass .*', line: '        proxy_pass          http://127.0.0.1:{{ internal_ports.bitwarden }};' }
    - { regexp: '.*server_name .*', line: '        server_name vault.{{ domain }} www.vault.{{ domain }};' }

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Run cert Script
  shell: "/usr/bin/certbot --nginx -noninteractive --domains {{ domain }}"

- name: Cron-Update
  cron:
    name: update system
    minute: "0"
    hour: "0"
    day: "2"
    job: "certbot --nginx renew"
