---
- name: Add repos for Tor
  shell: echo "deb     [signed-by=/usr/share/keyrings/tor-archive-keyring.gpg] https://deb.torproject.org/torproject.org $(lsb_release -cs) main \ndeb-src [signed-by=/usr/share/keyrings/tor-archive-keyring.gpg] https://deb.torproject.org/torproject.org $(lsb_release -cs) main" > /etc/apt/sources.list.d/tor.list
  when: ansible_distribution == 'Debian'

- name: Add GPG key for Tor
  ansible.builtin.apt_key:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    keyring: /usr/share/keyrings/tor-archive-keyring.gpg
    state: present

- name: Update repos
  package:
    update_cache: yes
    upgrade: yes

- name: Install Tor
  package:
    name:
      - tor
      - deb.torproject.org-keyring
    state: latest

- name: Config Tor port and directory
  lineinfile:
    dest: /etc/tor/torrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^#HiddenServiceDir.*', line: 'HiddenServiceDir /var/lib/tor/hidden_service/' }
    - { regexp: '^#HiddenServicePort.*', line: 'HiddenServicePort 80 127.0.0.1:80' }
  register: tor_config

- name: Restart Tor
  service:
    name: tor
    state: restarted
  when: tor_config.changed

- name: Retrieve Onion address
  command: cat /var/lib/tor/hidden_service/hostname
  register: onion_address

- debug:
    msg:
      - "⮶ THIS IS YOUR ONION ADDRESS ⮷"
      - "{{ onion_address.stdout }}"
