---
- name: Autoremove
  apt:
    autoremove: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install server packages
  package:
    name: "{{ packages.server }}"
    state: latest

- name: Install snaps
  snap:
    name:
      - core
      - nextcloud
    state: present
  register: install

- name: UFW deny all except HTTP and HTTPS
  ufw:
    state: enabled
    policy: deny
    rule: allow
    port: "{{ item }}"
  with_items:
    - '80'
    - '443'

- name: UFW limit ssh traffic
  ufw:
    rule: limit
    port: '22'

- name: Setup Nextcloud port
  shell: "snap set nextcloud ports.http={{ internal_ports.nextcloud }}"
  when: install.changed

- name: Setup Nextcloud admin account
  shell: '/snap/bin/nextcloud.manual-install {{ username }} {{ pwd }}'
  when: install.changed

- name: Ensure Nextcloud prefers HTTPS
  shell: '/snap/bin/nextcloud.occ config:system:set overwriteprotocol --value="https"'
  when: install.changed

- name: Config Nextcloud trusted domain
  lineinfile:
    dest: /var/snap/nextcloud/current/nextcloud/config/config.php
    regexp: ".*0 => 'localhost'.*"
    line: "1 => 'cloud.{{ domain }}'"

- name: Cron - Keep system updated
  cron:
    name: update system
    weekday: "0"
    minute: "30"
    hour: "2"
    job: "apt -y update && apt -y upgrade"
