---
- name: APT Autoremove
  apt:
    autoremove: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Server Packages
  package:
    name: "{{ packages.server }}"
    state: latest

- name: Install snaps
  snap:
    name:
      - core
      - nextcloud
    state: present
  register: install

- name: Change Nextcloud HTTP port
  shell: "snap set nextcloud ports.http={{ internal_ports.nextcloud }}"
  when: install.changed

- name: Create BitWarden User
  user:
    name: bitwarden
    password: "{{ pwd | password_hash('sha512') }}"
    shell: /bin/bash
    groups:
      - docker

- name: Restart Docker
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - docker
    - containerd

- name: Setup ssh For {{ users.bitwarden }}
  authorized_key:
    user: "{{ users.bitwarden }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Create Bitwarden dir
  file:
    path: /opt/bitwarden
    state: directory
    owner: bitwarden
    group: bitwarden
    mode: '0700'
    recurse: yes
