- name: Modify zshrc
  shell: "sed -Ee '/.*NVM.*/d' -Ee '/.*NODE.*/d' -Ee '/.*lua.*/d' ./dotfiles/base/.zshrc -i"

- name: Modify init.vim
  shell: "sed '/^source.*/d' ./.config/nvim/init.vim -i"

- name: Stow Basic Dotfiles
  shell: 
    cmd: "stow -R {{ item }}"
    chdir: dotfiles
  with_items: 
    - base
    - fontconfig
    - vifm
