---
- name: APT Autoremove
  apt:
    autoremove: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Server Packages
  package:
    name: "{{ packages.server }}"
    state: latest

- name: UFW Deny all except HTTP and HTTPS
  ufw:
    state: enabled
    policy: deny
    rule: allow
    port: "{{ item }}"
  with_items:
    - '80'
    - '443'

- name: UFW Limit ssh
  ufw:
    rule: limit
    port: '22'

- name: Install snaps
  snap:
    name:
      - core
      - nextcloud
    state: present
  register: install

- name: Change Nextcloud HTTP port
  shell: "snap set nextcloud ports.http={{ internal_ports.nextcloud }}"
  when: install.changed

- name: Setup Nextcloud admin account
  shell: '/snap/bin/nextcloud.manual-install {{ username }} {{ pwd }}'
  when: install.changed

- name: Ensure HTTPS is preferred
  shell: '/snap/bin/nextcloud.occ config:system:set overwriteprotocol --value="https"'
  when: install.changed

- name: Config trusted domain
  lineinfile:
    dest: /var/snap/nextcloud/current/nextcloud/config/config.php
    regexp: ".*0 => 'localhost'.*"
    line: "1 => 'cloud.{{ domain }}'"

- name: Create BitWarden User
  user:
    name: bitwarden
    shell: /bin/bash
    groups:
      - docker

- name: Restart Docker
  service:
    name: docker
    state: restarted

- name: Setup ssh For {{ users.bitwarden }}
  authorized_key:
    user: "{{ users.bitwarden }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Create Bitwarden dir
  file:
    path: /opt/bitwarden
    state: directory
    owner: bitwarden
    group: bitwarden
    mode: '0700'
    recurse: yes

- name: Cron-Update
  cron:
    name: update system
    weekday: "0"
    minute: "30"
    hour: "2"
    job: "apt -y update && apt -y upgrade"
