---
- name: Install docker
  become: true
  package:
    name:
      - docker
      - docker-compose
    state: latest

- name: Run container
  docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    env:
      ADMIN_TOKEN: "{{ admin_token }}"
      SIGNUPS_ALLOWED: "{{ signups }}"
    detach: yes
    state: started
    volumes:
      - "/vw-data/:/data/"
    ports:
      - 82:80

- name: Keep vaultwarden updated
  become: true
  cron:
    name: nuke vaultwarden
    state: present
    weekday: "0"
    minute: "0"
    hour: "3"
    job: "/usr/bin/docker system prune -f"

- name: Keep vaultwarden updated
  become: true
  cron:
    name: update vaultwarden
    state: present
    weekday: "0"
    minute: "0"
    hour: "3"
    job: /usr/bin/docker run -d --name vaultwarden -e ADMIN_TOKEN={{ admin_token }} -e SIGNUPS_ALLOWED={{ signups }} -v /vw-data/:/data/ -p 82:80 vaultwarden/server:latest
