---
- name: Run container
  docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    env:
      ADMIN_TOKEN: "{{ admin_token }}"
      SIGNUPS_ALLOWED: "{{ signups }}"
    detach: yes
    state: started
    volumes:
      - "/vw-data/:/data/"
    ports:
      - "{{ internal_ports.vaultwarden }}:80"

- name: Cron - Keep vaultwarden updated
  cron:
    name: update vaultwarden
    weekday: "0"
    minute: "0"
    hour: "3"
    job: "{{ item }}"
  with_items:
    - "/usr/bin/docker system prune -f"
    - "/usr/bin/docker run -d --name vaultwarden -e ADMIN_TOKEN={{ admin_token }} -e SIGNUPS_ALLOWED={{ signups }} -v /vw-data/:/data/ -p {{ internal_ports.vaultwarden }}:80 vaultwarden/server:latest"
