---
- name: Add GPG key
  apt_key:
    url: "{{ key_url }}"
    keyring: "/usr/share/keyrings/{{ pkg_name }}-archive-keyring.gpg"
    state: present

- name: Add repos
  copy:
    dest: "/etc/apt/sources.list.d/{{ pkg_name }}.list"
    content: |
      deb     [signed-by=/usr/share/keyrings/{{ pkg_name }}-archive-keyring.gpg] {{ pkg_url }} {{ ansible_distribution_release }} {{  components | join(' ') }}
      deb-src     [signed-by=/usr/share/keyrings/{{ pkg_name }}-archive-keyring.gpg] {{ pkg_url }} {{ ansible_distribution_release }} {{  components | join(' ') }}

- name: Update repos
  package:
    update_cache: true
