---
- name: Update system
  package:
    update_cache: true
    upgrade: true

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "git"
    - "zsh"
    - "stow"

- name: Clone dotfiles
  become_user: "{{ username }}"
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "/home/{{ username }}/dotfiles"
    track_submodules: true
    force: true

- name: Set zsh as default shell
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  with_items:
    - "{{ username }}"
    - root

- name: Unstow dotfiles
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "stow -R *"
    chdir: "/home/{{ username }}/dotfiles"
  changed_when: true
