---
- name: Clone dotfiles
  become_user: "{{ username }}"
  git:
    repo: "{{ dotfiles }}"
    dest: "/home/{{ username }}/dotfiles"
    track_submodules: true
    force: true

- name: Set zsh as default shell
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  with_items:
    - "{{ username }}"
    - root

- name: Use plugin-less nvim config
  become_user: "{{ username }}"
  shell: 'rm /home/{{ username }}/dotfiles/nvim/.config/nvim/init.vim && cp /home/{{ username }}/dotfiles/nvim/.config/nvim/base-init.vim /home/{{ username }}/dotfiles/nvim/.config/nvim/init.vim'

- name: Unstow dotfiles
  become_user: "{{ username }}"
  shell:
    cmd: "stow -R {{ item }}"
    chdir: "/home/{{ username }}/dotfiles"
  with_items:
    - base
    - zsh
    - nvim
    - fontconfig
    - vifm
