---
- name: Clone dotfiles
  become_user: "{{ username }}"
  git:
    repo: "{{ dotfiles }}"
    dest: "/home/{{ username }}/dotfiles"
    track_submodules: true
    force: true

- name: Set zsh as default shell
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  with_items:
    - "{{ username }}"
    - root

- name: Use plugin-less nvim config
  become_user: "{{ username }}"
  block:
    - name: Remove init.vim
      file:
        state: absent
        path: "/home/{{ username }}/dotfiles/nvim/.config/nvim/init.vim"

    - name: Set plugin-less config
      copy:
        src: "/home/{{ username }}/dotfiles/nvim/.config/nvim/base-init.vim"
        dest: "/home/{{ username }}/dotfiles/nvim/.config/nvim/init.vim"
        remote_src: true

- name: Unstow dotfiles
  become_user: "{{ username }}"
  ansible.builtin.command:
    cmd: "stow -R {{ item }}"
    chdir: "/home/{{ username }}/dotfiles"
  with_items:
    - base
    - zsh
    - nvim
    - fontconfig
    - vifm
  changed_when: true
