---
- name: Clone dotfiles
  git:
    repo: "{{ dotfiles }}"
    dest: "/home/{{ username }}/dotfiles"
    force: yes
    track_submodules: yes

- name: Set zsh as default shell
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  with_items:
    - "{{ username }}"
    - root

- name: Clone nvim config
  git:
    repo: "{{ nvim_config }}"
    dest: "/home/{{ username }}/.config/nvim"
    force: yes

- name: Unstow dotfiles
  shell:
    cmd: "stow -R {{ item }}"
    chdir: "/home/{{ username }}/dotfiles"
  with_items:
    - base
    - custom-zsh
    - fontconfig
    - vifm
