---
- name: Clone dotfiles
  git:
    repo: "{{ dotfiles }}"
    dest: "/home/{{ username }}/dotfiles"
    force: true
    track_submodules: true

- name: Set zsh as default shell
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  with_items:
    - "{{ username }}"
    - root

- name: Clone nvim config
  git:
    repo: "{{ nvim_config }}"
    dest: "/home/{{ username }}/.config/nvim"
    force: true

- name: Use plugin-less config
  shell: 'rm /home/{{ username }}/.config/nvim/init.vim && cp /home/{{ username }}/.config/nvim/base-init.vim /home/{{ username }}/.config/nvim/init.vim'

- name: Unstow dotfiles
  shell:
    cmd: "stow -R {{ item }}"
    chdir: "/home/{{ username }}/dotfiles"
  with_items:
    - base
    - custom-zsh
    - fontconfig
    - vifm
