---
- name: Update system
  become: true
  package:
    update_cache: true
    upgrade: true

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ basic_packages }}"

- name: Check if nvim config is present
  stat:
    path: "/home/{{ username }}/dotfiles/nvim"
  register: nvim_config

- name: Build nvim from source
  block:

    - name: Install nvim dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ nvim_deps }}"

    - name: Clone
      become_user: "{{ username }}"
      git:
        repo: "https://github.com/neovim/neovim"
        dest: "/home/{{ username }}/neovim"
        version: stable
        force: true

    - name: Make Clean
      make:
        chdir: "/home/{{ username }}/neovim"
        target: distclean

    - name: Make Build
      make:
        chdir: "/home/{{ username }}/neovim"
        target: all
        params:
          CMAKE_BUILD_TYPE: Release

    - name: Make Install
      become: true
      make:
        chdir: "/home/{{ username }}/neovim"
        target: install

  when: nvim_config.stat.isdir is defined and nvim_config.stat.isdir
