- name: Custom dotfiles
  when: dotfiles_repo is defined
  block:
    - name: Clone dotfiles
      import_tasks: dotfiles.yml
      when: dotfiles_repo is defined and dotfiles_repo | length > 0

    - name: Copy configs for root
      become: true
      import_tasks: root.yml

      when: dotfiles_repo is defined and dotfiles_repo | length > 0
    - name: Install basick packages
      import_tasks: install.yml

    - name: Set zsh as default shell
      become: true
      user:
        name: "{{ item }}"
        shell: /usr/bin/zsh
      with_items:
        - "{{ username }}"
        - root
