---
- name: Copy for root user
  copy:
    src: "/home/{{ username }}/{{ item.src }}"
    dest: "/root/{{ item.dest }}"
    remote_src: yes
  with_items:
    - {src: "dotfiles/base/.zshrc", dest: ".zshrc"}
    - {src: "dotfiles/custom-zsh/.config/custom-zsh", dest: ".config/"}
    - {src: ".config/nvim", dest: ".config/"}

- name: Set base init for root
  shell: 'rm /root/.config/nvim/init.vim && cp /root/.config/nvim/base-init.vim /root/.config/nvim/init.vim'
