---
- name: Copy for root user
  copy:
    src: "/home/{{ username }}/dotfiles"
    dest: "/root/"
    owner: root
    group: root
    remote_src: true
    mode: 0644

- name: Unstow dotfiles
  shell:
    cmd: "stow -R *"
    chdir: "/root/dotfiles"
  changed_when: true
