---
- name: Copy for root user
  copy:
    src: "/home/{{ username }}/{{ item.src }}"
    dest: "/root/{{ item.dest }}"
    owner: root
    group: root
    remote_src: true
  with_items:
    - {src: "dotfiles/base/.zshrc", dest: ".zshrc"}
    - {src: "dotfiles/custom-zsh/.config/custom-zsh", dest: ".config/"}
    - {src: ".config/nvim", dest: ".config/"}
