---
- name: Install docker
  package:
    name:
      - docker
      - docker-compose
    state: latest

- name: Make sure Docker is running and enabled
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
