---
- name: Install gawk
  package:
    name: gawk
    state: present
- name: Clone repo

  git:
    repo: https://github.com/searxng/searxng
    dest: searxng
    force: true

- name: Install
  shell: "{{ item }}"
  with_items:
    - FORCE_TIMEOUT=0 ./searxng/utils/searxng.sh install all

- name: Transfer searx config
  copy:
    src: searx.yml
    dest: /etc/searxng/settings.yml

- name: Restart uwsgi
  service:
    name: uwsgi
    state: restarted
    enabled: true
