---
- name: Monthly updates
  become_user: "{{ username }}"
  cron:
    name: update searx
    state: present
    special_time: monthly
    job: >
      /usr/bin/docker stop {{ container }} &
      /usr/bin/docker rm {{ container }} &
      /usr/bin/docker pull {{ image }} &
      /usr/bin/docker run -d
      --restart unless-stopped
      --name {{ container }}
      -e BASE_URL=false
      -e INSTANCE_NAME=SearX!
      -v /home/{{ username }}/searxng:/etc/searxng
      -p {{ service.searx.port }}:8080
      {{ image }}
