---
- name: Keep searxng updated
  cron:
    name: update searx
    state: present
    special_time: monthly
    job: >
      /usr/bin/docker pull searxng/searxng:latest &
      /usr/bin/docker run --rm -d
      --name searx
      --restart unless-stopped
      -e BASE_URL=false
      -e INSTANCE_NAME=SearX!
      -v /home/{{ username }}/searxng:/etc/searxng
      -p {{ ports.searx }}:8080
      searxng/searxng"
