---
- name: Install docker and compose
  package:
    name:
      - docker
      - docker-compose
    state: present

- name: Start and enable docker
  become: true
  systemd:
    name: docker
    daemon_reload: true
    state: started
    enabled: true
