---
- name: Autoremove
  apt:
    autoremove: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Update system
  package:
    update_cache: true
    upgrade: true

- name: Cron - Keep system updated
  cron:
    name: update system
    state: present
    weekday: "0"
    minute: "30"
    hour: "2"
    job: "apt -y update && apt -y upgrade"
