---
packages:
  basic:
    - neovim
    - exa
    - delta
    - zsh
    - fzf
    - git
    - ripgrep
    - rsync
    - stow
    - ufw
    - htop
    - expect
    - vifm
    - zsh
    - tree
    - python3-pip
    - libxtst-dev
    - libjpeg-dev
    - zlib1g-dev
    - curl
  server:
    - nginx
    - python3-certbot-nginx
    - gpg
    - apt-transport-https
    - snapd
    - docker
    - docker-compose
login_user: ansible
