---
- name: Create backup dir
  file:
    path: "{{ backup_dir }}/{{ service.cloud.subdomain }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Backup nextcloud
  cron:
    name: backup nextcloud
    state: present
    special_time: monthly
    job: >
      /snap/bin/nextcloud.export &
      rm -rf {{ backup_dir }}/{{ service.cloud.subdomain }}/*
      mv /var/snap/nextcloud/common/backups/* {{ backup_dir }}/{{ service.cloud.subdomain }}
