---
- name: Backup
  vars:
    backup: "{{ service.cloud.subdomain }}"
    command: >
      /snap/bin/nextcloud.export &
      rm -rf {{ backup_dir }}/{{ backup }}/*
      mv /var/snap/nextcloud/common/backups/* {{ backup_dir }}/{{ backup }}
  import_role:
    name: subroles/backup
