---
- name: Create backup dir
  file:
    path: "/home/{{ username }}/backups/cloud"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Backup nextcloud
  cron:
    name: backup nextcloud
    state: present
    special_time: monthly
    job: >
      /snap/bin/nextcloud.export &
      rm -rf /home/{{ username }}/backups/cloud/*
      mv /var/snap/nextcloud/common/backups/* /home/{{ username }}/backups/cloud
