---
- name: Monthly backups
  cron:
    name: "backup cloud"
    state: "present"
    special_time: "weekly"
    job: >
      /bin/mkdir -p {{ backup_dir }}/cloud &
      /bin/rm -rf /var/snap/nextcloud/common/backups/* &
      /snap/bin/nextcloud.export &
      /bin/rm -rf {{ backup_dir }}/cloud/* &
      /bin/mv /var/snap/nextcloud/common/backups/* {{ backup_dir }}/cloud &
      chown -R {{ username }}:{{ username }} {{ backup_dir }}
