---
- name: Config nextcloud port
  command: "snap set nextcloud ports.http={{ service.cloud.port }}"
  when: install.changed

- name: Specify php memory limit
  command: "snap set nextcloud php.memory-limit=512M"
  when: install.changed

- name: Config nextcloud admin account
  command: '/snap/bin/nextcloud.manual-install {{ nextcloud_username }} {{ user_password }}'
  when: install.changed

- name: Ensure nextcloud prefers HTTPS
  command: '/snap/bin/nextcloud.occ config:system:set overwriteprotocol --value="https"'
  when: install.changed

- name: Ensure nextcloud trusts domain
  block:
    - name: localhost
      command: '/snap/bin/nextcloud.occ config:system:set trusted_domains 0 --value="localhost"'
    - name: cloud subdomain
      command: '/snap/bin/nextcloud.occ config:system:set trusted_domains 1 --value="{{ service.cloud.subdomain }}.{{ domain }}"'
  when: install.changed
