---
- name: Config nextcloud port
  command: "snap set nextcloud ports.http={{ service.cloud.port }}"
  when: install.changed

- name: Config nextcloud admin account
  command: '/snap/bin/nextcloud.manual-install {{ nextcloud_username }} {{ user_password }}'
  when: install.changed

- name: Ensure nextcloud prefers HTTPS
  command: '/snap/bin/nextcloud.occ config:system:set overwriteprotocol --value="http"'
  when: install.changed

- name: Config nextcloud trusted domain
  lineinfile:
    dest: /var/snap/nextcloud/current/nextcloud/config/config.php
    insertafter: "0 => 'localhost'"
    line: "1 => 'cloud.{{ domain }}'"
    state: present
