---
- name: Nextcloud - Docker
  vars: 
    container: "nextcloud"
    image: "nextcloud"
    data_dir: "/{{ service.cloud.subdomain }}-data/"
    backup_dir: "{{ common_backup_dir }}/{{ service.cloud.subdomain }}"
  block:
    - import_tasks: setup.yml
    - import_tasks: run.yml
    - import_tasks: maintenance.yml
