---
- name: Run container
  become_user: "{{ username }}"
  docker_container:
    name: "{{ container }}"
    image: "{{ image }}"
    pull: true
    detach: true
    state: "started"
    restart_policy: unless-stopped
    env:
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud_username }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "localhost {{ service.cloud.subdomain }}.{{ domain }}"
      SQLITE_DATABASE: "nextcloud_db"
    volumes:
      - "{{ data_dir }}:/data/"
    ports:
      - "{{ service.cloud.port }}:80"

