- name: Run container
  docker_container:
    name: "{{ container }}"
    image: "{{ image }}"
    pull: true
    detach: true
    state: "started"
    restart_policy: unless-stopped
    env_file: "/home/{{ username }}/docker_env_files/nextcloud.env"
    volumes:
      - "{{ data_dir }}/data/:/var/www/html/data"
      - "{{ data_dir }}/apps/:/var/www/html/apps"
      - "{{ data_dir }}/config/:/var/www/html/config"
    ports:
      - "{{ service.cloud.port }}:80"
