---
- name: Setup docker
  import_role:
    name: common_roles/docker

- name: Ensure port is available
  import_role:
    name: common_roles/free_port
  vars:
    port_to_free: "{{ service.cloud.port }}"

