---
# TODO. find a way to expose onion address
# TODO. turn USE_MODSECURITY on when bunkerweb updates CRS to > v3.4.0
# https://github.com/coreruleset/coreruleset/issues/3049#issuecomment-1346309713
- name: Copy config file
  template:
    src: bunker.conf
    dest: "/opt/bunkerweb/variables.env"

- name: Symlink website
  file:
    src: "/home/{{ username }}/website"
    dest: "/opt/bunkerweb/www/{{ domain }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: link

- name: Enable and restart bunkerweb
  service:
    name: bunkerweb
    enabled: true
    state: restarted
