---
- name: Install specific versions
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "nginx=1.20.2-1~{{ ansible_distribution_release }}"
    - "bunkerweb=1.4.5"
    - "python3-certbot-nginx"

- name: Fix versions
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - nginx
    - bunkerweb
