---
- name: Add GPG key for nginx
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    keyring: /usr/share/keyrings/nginx-archive-keyring.gpg
    state: present

- name: Add repos for nginx
  copy:
    dest: "/etc/apt/sources.list.d/nginx.list"
    content: |
      deb     [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/debian {{ ansible_distribution_release }} nginx

- block:
    - name: Check if bunkerweb is installed
      package_facts:
        manager: auto

    - name: Run bunkerweb setup script
      shell: 'curl -s https://packagecloud.io/install/repositories/bunkerity/bunkerweb/script.deb.sh | sudo bash'
      when: "'bunkerweb' not in ansible_facts.packages"

- name: Update repos
  package:
    update_cache: yes
    upgrade: yes
