---
- name: Setup nginx repos
  vars:
    pkg_name: "nginx"
    pkg_url: "http://nginx.org/packages/debian"
    key_url: "https://nginx.org/keys/nginx_signing.key"
    components:
      - "nginx"
  import_role:
    name: subroles/add_repo

- block:
    - name: Check if bunkerweb is installed
      package_facts:
        manager: auto

    - name: Run bunkerweb setup script
      shell: 'curl -s https://packagecloud.io/install/repositories/bunkerity/bunkerweb/script.deb.sh | sudo bash'
      when: "'bunkerweb' not in ansible_facts.packages"

- name: Update repos
  package:
    update_cache: true
