---
- name: Monthly updates
  cron:
    name: update gitea
    state: present
    special_time: monthly
    job: >
      /usr/bin/docker stop {{ container }};
      /usr/bin/docker rm {{ container }};
      /usr/bin/docker pull {{ image }};
      /usr/bin/docker run -d
      --restart unless-stopped
      --name {{ container }}
      -e GITEA__security__INSTALL_LOCK=true
      -e GITEA__service__DISABLE_REGISTRATION=true
      -e GITEA__repository__ROOT=/data/gitea/git/repositories
      -e GITEA__repository__DEFAULT_BRANCH=master
      -e GITEA__lfs__PATH=/data/gitea/git/lfs
      -e GITEA__server__DOMAIN={{ git_domain }}
      -e GITEA__server__SSH_DOMAIN={{ git_domain }}
      -e GITEA__server__ROOT_URL=http://{{ git_domain }}
      -e USER_UID={{ git_uid }}
      -e USER_GID={{ git_gid }}
      -v {{ data_dir }}/:/data/
      -v /etc/timezone:/etc/timezone:ro
      -v /etc/localtime:/etc/localtime:ro
      -p {{ service.vault.port }}:3000
      -p 2222:22
      {{ image }}

- name: Weekly backups
  cron:
    name: "backup gitea"
    state: "present"
    special_time: "weekly"
    job: >
      sudo /bin/cp -urp {{ data_dir }}/* {{ backup_dir }}
