# TODO: Swap for Forgejo https://forgejo.org/docs/latest/admin/installation-docker/
- name: Gitea - Docker
  vars:
    container: "gitea"
    image: "gitea/gitea:latest"
    data_dir: "/{{ service.gitea.subdomain }}-data"
    backup_dir: "{{ common_backup_dir }}/{{ service.gitea.subdomain }}"
    git_uid: "1005"
    git_gid: "1005"
    git_domain: "{{ service.gitea.subdomain }}.{{ domain }}"
  block:
    - import_tasks: ssh_passthrough.yml
    - import_tasks: setup.yml
    - import_tasks: run.yml
      tags: ignore-ci # TODO: docker in ci
    - import_tasks: maintenance.yml
