- name: Run container
  docker_container:
    name: "{{ container }}"
    image: "{{ image }}"
    pull: true
    detach: true
    state: "started"
    restart_policy: unless-stopped
    env_file: "/home/{{ username }}/docker_env_files/gitea.env"
    volumes:
      - "{{ data_dir }}/:/data/"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/git/.ssh/:/data/git/.ssh
    ports:
      - "{{ service.gitea.port }}:3000"
      - "2222:22"

- name: Create admin user
  block:
    - name: Wait for gitea db
      wait_for:
        timeout: 4

    - name: List existing users
      community.docker.docker_container_exec:
        container: "{{ container }}"
        user: "git"
        command: "gitea admin user list"
      register: user_list

    - name: Create admin user if not present
      when: "gitea_username not in user_list.stdout"
      community.docker.docker_container_exec:
        container: "{{ container }}"
        user: "git"
        command: "gitea admin user create --admin --username {{ gitea_username }} --password {{ gitea_password }} --email {{ email }}"
