- name: Setup git user for SSH passthrough
  become: true
  vars:
    git_user: "git"
  block:

    - name: Create "{{ git_user }}" group
      group:
        name: "{{ git_user }}"
        gid: "{{ git_gid }}"

    - name: Create "{{ git_user }}" user
      user:
        name: "{{ git_user }}"
        uid: "{{ git_uid }}"
        group: "{{ git_gid }}"
        system: true
        createhome: true
        home: "/home/{{ git_user }}"

    - name: Fake gitea cmd
      copy:
        dest: "/usr/local/bin/gitea"
        content: |
          #!/bin/sh
          ssh -p 2222 -o StrictHostKeyChecking=no {{ git_user }}@127.0.0.1 "SSH_ORIGINAL_COMMAND=\"$SSH_ORIGINAL_COMMAND\" $0 $@"
        mode: 0755

    # Needed for ansible's become_user shenanigans
    - name: Install acl
      import_role:
        name: common_roles/install_latest
      vars:
        packages:
          - "acl"
          - "sudo"

    - name: SSH for {{ git_user }}
      become: true
      become_user: "{{ git_user }}"
      block:

        - name: Mkdir ssh
          file:
            state: directory
            path: "/home/{{ git_user }}/.ssh"
            mode: 0700

        - name: Ssh key pair
          openssh_keypair:
            path: "/home/{{ git_user }}/.ssh/id_rsa"

        - name: Slurp public key
          slurp:
            src: "/home/{{ git_user }}/.ssh/id_rsa.pub"
          register: public_key

        - name: Add to auth_keys
          authorized_key:
            user: "{{ git_user }}"
            state: present
            key: "{{ public_key['content'] | b64decode }}"

- name: Enable and restart ssh
  become: true
  tags: ignore-ci # ci doesn't boot with systemd
  service:
    name: sshd
    enabled: true
    state: restarted
