---
- name: Update system
  package:
    update_cache: true
    upgrade: true

- name: Install packages
  package:
    name: argon2
    state: present

  # TODO.test
- name: Create admin admin_token
  shell: echo -n "{{ vaultwarden_password }}" | argon2 "$(openssl rand -base64 32)" -e -id -k 19456 -t 2 -p 1
  register: admin_token
