---
- name: Setup docker
  import_role:
    name: subroles/docker

- name: Run container
  docker_container:
    name: "vaultwarden"
    image: "vaultwarden/server:latest"
    pull: true
    detach: true
    state: "started"
    restart_policy: unless-stopped
    env:
      ADMIN_TOKEN: "{{ admin_token }}"
      SIGNUPS_ALLOWED: "{{ allow_signups | default('false') }}"
    volumes:
      - "/vw-data/:/data/"
    ports:
      - "{{ service.vault.port }}:80"

- name: Monthly updates
  cron:
    name: update vaultwarden
    state: present
    special_time: monthly
    job: >
      /usr/bin/docker pull vaultwarden/server:latest &
      /usr/bin/docker run -d
      --rm
      --pull=always
      --name vaultwarden
      --restart unless-stopped
      -e ADMIN_TOKEN={{ admin_token }}
      -e SIGNUPS_ALLOWED={{ allow_signups | default('false') }}
      -v /vw-data/:/data/
      -p {{ service.vault.port }}:80
      vaultwarden/server:latest"

- name: Monthly backups
  vars:
    backup: "{{ service.vault.subdomain }}"
    command: >
      rm -rf {{ backup_dir }}/{{ backup }}/*
      cp /vw-data/db.sqlite* {{ backup_dir }}/{{ backup }}
  import_role:
    name: subroles/backup
