---
- name: Monthly updates
  become_user: "{{ username }}"
  cron:
    name: update vaultwarden
    state: present
    special_time: monthly
    job: >
      /usr/bin/docker stop {{ container }} &
      /usr/bin/docker rm {{ container }} &
      /usr/bin/docker pull {{ image }} &
      /usr/bin/docker run -d
      --restart unless-stopped
      --name {{ container }}
      -e ADMIN_TOKEN={{ admin_token.stdout }}
      -e SIGNUPS_ALLOWED=false
      -v {{ data_dir }}:/data/
      -p {{ service.vault.port }}:80
      {{ image }}

- name: Weekly backups
  cron:
    name: "backup vault"
    state: "present"
    special_time: "weekly"
    job: >
      /bin/mkdir -p {{ backup_dir }} &
      /bin/rm -rf {{ backup_dir }}/* &
      /bin/cp {{ data_dir }}db.sqlite* {{ backup_dir }} &
      /bin/cp -r {{ data_dir }}attachments {{ backup_dir }} & 
      chown -R {{ username }}:{{ username }} {{ backup_dir }}
