---
- name: Setup docker
  import_role:
    name: subroles/docker

- name: Setup vault
  import_tasks: vault.yml

- name: Keep vaultwarden updated
  import_tasks: update.yml

- name: Keep vaultwarden backed up
  import_tasks: backup.yml
