---
- name: Run container
  docker_container:
    name: "{{ container }}"
    image: "{{ image }}"
    pull: true
    detach: true
    state: "started"
    restart_policy: unless-stopped
    env_file: "/home/{{ username }}/docker_env_files/vaultwarden.env"
    volumes:
      - "{{ data_dir }}/:/data/"
    ports:
      - "{{ service.vault.port }}:80"
