---
- name: Run container
  docker_container:
    name: "{{ container }}"
    image: "{{ image }}"
    pull: true
    detach: true
    state: "started"
    restart_policy: unless-stopped
    env:
      ADMIN_TOKEN: "{{ admin_token.stdout }}"
      SIGNUPS_ALLOWED: "false"
    volumes:
      - "{{ data_dir }}/:/data/"
    ports:
      - "{{ service.vault.port }}:80"
