---
- name: Keep vaultwarden updated
  cron:
    name: update vaultwarden
    state: present
    special_time: monthly
    job: >
      "/usr/bin/docker stop vaultwarden &
      /usr/bin/docker rm vaultwarden &
      /usr/bin/docker pull vaultwarden/server:latest &
      /usr/bin/docker run -d
      --name vaultwarden
      -e ADMIN_TOKEN={{ admin_token }}
      -e SIGNUPS_ALLOWED={{ allow_signups | default('false') }}
      -v /vw-data/:/data/
      -p 82:80 vaultwarden/server:latest"
