---
- name: Keep vaultwarden updated
  cron:
    name: update vaultwarden
    state: present
    special_time: monthly
    job: >
      /usr/bin/docker pull vaultwarden/server:latest &
      /usr/bin/docker run -d
      --rm
      --pull=always
      --name vaultwarden
      --restart unless-stopped
      -e ADMIN_TOKEN={{ admin_token }}
      -e SIGNUPS_ALLOWED={{ allow_signups | default('false') }}
      -v /vw-data/:/data/
      -p {{ ports.vaultwarden }}:80
      vaultwarden/server:latest"
