---
- name: Run container
  docker_container:
    name: vaultwarden
    image: vaultwarden/server:latest
    restart_policy: unless-stopped
    env:
      ADMIN_TOKEN: "{{ admin_token }}"
      SIGNUPS_ALLOWED: "{{ allow_signups | default('false') }}"
    detach: yes
    state: started
    volumes:
      - "/vw-data/:/data/"
    ports:
      - "{{ ports.vaultwarden }}:80"
