---
- name: Run container
  docker_container:
    name: "vaultwarden"
    image: "vaultwarden/server:latest"
    pull: true
    detach: true
    state: "started"
    restart_policy: unless-stopped
    env:
      ADMIN_TOKEN: "{{ admin_token }}"
      SIGNUPS_ALLOWED: "{{ allow_signups | default('false') }}"
    volumes:
      - "/vw-data/:/data/"
    ports:
      - "{{ service.vault.port }}:80"
