---
- name: Update system
  become: true
  package:
    update_cache: true
    upgrade: true

- name: Install fail2ban
  package:
    name: fail2ban
    state: present

- name: Copy config files
  template:
    src: "{{ item.template }}"
    dest: "/etc/fail2ban/{{ item.conf_file }}"
    mode: 0644
  with_items:
    - template: "cloudflare_action"
      conf_file: "action.d/cloudflare.local"
    - template: "mail_action"
      conf_file: "action.d/sendmail-common.local"
    - template: "common_filter"
      conf_file: "filter.d/common"
    - template: "jail"
      conf_file: "jail.local"

- name: Enable and restart fail2ban
  become: true
  service:
    name: fail2ban
    enabled: true
    state: restarted
