---
# TODO.CloudFlare setup https://niksec.com/using-fail2ban-with-cloudflare/
# TODO.Vault web and admin setup https://github.com/dani-garcia/vaultwarden/wiki/Fail2Ban-Setup#setup-for-web-vault
- name: Install fail2ban
  package:
    name: fail2ban
    state: present

- name: Disable e-mail notifications on jail stop and start
  template:
    src: "fail2ban"
    dest: "/etc/fail2ban/action.d/sendmail-common.local"
    mode: 0644

- name: Install the jail file
  template:
    src: "jail"
    dest: "/etc/fail2ban/jail.local"
    mode: 0644

- name: Enable and restart fail2ban
  service:
    name: fail2ban
    enabled: true
    state: restarted
