- name: Install packages
  import_role:
    name: common_roles/install_latest
  vars:
    packages: "cron"

- name: Autoremove
  apt:
    autoremove: true

- name: Update system
  package:
    update_cache: true
    upgrade: true

- name: Monthly updates
  cron:
    name: update system
    state: present
    special_time: monthly
    job: "apt -y update && apt -y upgrade && systemctl reboot"
