---
- name: Setup custom config files
  include_vars: vars.yml
- block:
  - name: Setup
    import_tasks: setup.yml

  - name: Clone dotfiles
    import_tasks: dotfiles.yml

  - name: Copy configs for root
    import_tasks: root.yml
