---
- name: Update system
  become: true
  package:
    update_cache: yes
    upgrade: yes

- name: Install basic packages
  become: true
  package:
    name: "{{ packages.basic }}"
    state: latest
