---
- name: Setup tor repos
  vars:
    pkg_name: "tor"
    pkg_url: "https://deb.torproject.org/torproject.org"
    key_url: "https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc"
    components:
      - "main"
  import_role:
    name: common_roles/add_repo

- name: Install Tor
  package:
    name:
      - tor
      - deb.torproject.org-keyring
    state: latest
