---
- name: Install Tor
  package:
    name:
      - tor
      - deb.torproject.org-keyring
    state: present

- name: Config tor port and directory
  lineinfile:
    dest: /etc/tor/torrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^#?HiddenServiceDir"
      line: "HiddenServiceDir /var/lib/tor/hidden_service/"
    - regexp: "^#?HiddenServicePort"
      line: "HiddenServicePort {{ ports.http }} 127.0.0.1:{{ ports.http }}"

- name: Enable and restart tor
  become: true
  service:
    name: tor
    enabled: true
    state: restarted
