---
- name: Add repos for tor
  template:
    src: "tor_repos"
    dest: "/etc/apt/sources.list.d/tor.list"

- name: Add GPG key for tor
  apt_key:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    keyring: /usr/share/keyrings/tor-archive-keyring.gpg
    state: present

- name: Update repos
  package:
    update_cache: yes
    upgrade: yes

- name: Install Tor
  package:
    name:
      - tor
      - deb.torproject.org-keyring
    state: latest
