- name: Install packages
  import_role:
    name: common_roles/install_latest
  vars:
    packages: "ufw"

- name: UFW deny all except HTTP and HTTPS
  tags: ignore-ci # no iptables in docker ci
  ufw:
    state: enabled
    policy: deny
    rule: allow
    port: "{{ item }}"
  with_items:
    - "{{ ports.http }}"
    - "{{ ports.https }}"

- name: UFW limit ssh traffic
  tags: ignore-ci # no iptables in docker ci
  ufw:
    state: enabled
    rule: limit
    port: "{{ ports.ssh }}"
